### ISSUE TITLE
example input file missing

### ISSUE THREAD

**Issue by robomotic** [pwrliang/GeneralizedSuffixTree#1]
Hello there,
just read your paper very interesting approach, however to replicate your paper result and your code you should also include the input example files shown in your bar chart such as 5000_10000 until 20M_20.

Regards.

**Comment by pwrliang** [comment]
Hi there,
I have put the link of dataset on the README page. By the way, I'm not the author of the "ERA" paper. I just implemented the algorithm in that paper for a "College Bigdata Contest". I also have the code which written by the co-author of that paper. 

[ElasticRange_133_EraFixedAll](https://pwrliang.com/share/g_suffix_tree/ElasticRange_133_EraFixedAll.c)

`to compile the code:

Serial:

gcc -O3 <fileName>.c -o eraSerial

Parallel

mpicc -O3 -DPARALLEL <fileName>.c -o eraMPI`

Regards,
Liang

**Comment by robomotic** [comment]
Thanks a lot, I am downloading them now!
Also thanks for the ERA code, this is helpful as well.
